spring:
  application:
    name: DemoApp-sso
  
  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  
  devtools:
    restart:
      enabled: true

  # OAuth2 설정
  security:
    oauth2:
      client:
        # 등록된 클라이언트 정보
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver SSO
          kakao:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao SSO
            client-authentication-method: client_secret_post
        # Provider 설정
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id